### ISSUE TITLE
PostmarketOS mainline on oneplus 5T not booting to DE 

### ISSUE THREAD

**Issue by Mast3rwaf1z** [JamiKettunen/linux-mainline-oneplus5#6] opened 2021-12-30 00:59 UTC
Hi, I've been working on getting my pile of old ARM devices to do some cool stuff, mainly I want to get my old OnePlus 5T to boot PostmarketOS with a few different WM options.

There are a few issues here, WiFi doesn't work no matter the settings i give pmbootstrap

X11 does work if I use the downstream kernel but it does not work if I use the mainline kernel, which means I can't see anything at all no matter what I do with mainline

Wayland doesn't work for me at all

I know I have probably just missed something, since I can see on the wiki that Phosh works on the 5T.

**Comment by JamiKettunen** [comment] 2022-01-04 05:01
This sounds very much like a firmware problem, though even then simple(r) UIs should work with software rendering even without help of the GPU; if you can get an SSH shell with mainline, what's the version  from `apk info firmware-oneplus-msm8998`? it should be [`10.0.1-r1`](http://pkgs.postmarketos.org/package/master/postmarketos/aarch64/firmware-oneplus-msm8998). `linux-postmarketos-qcom-msm8998` should also be at [`5.16.0_rc6-r1`](http://pkgs.postmarketos.org/package/master/postmarketos/aarch64/linux-postmarketos-qcom-msm8998) as of now

You could also add a copy of your `pmbootstrap config` so I can attempt reproducing on my machine since I can't seem to get this to happen with the mainline kernel.

**Comment by Mast3rwaf1z** [comment] 2022-01-06 13:27
Hi, I've been busy with exams the last week so I haven't looked into it, I'll flash it after my exam tomorrow

**Comment by Mast3rwaf1z** [comment] 2022-01-07 12:20
okay apparently it seems to be working with mainline now after pulling from pmbootstrap, i don't know what changed, when i wrote the original post i had also just pulled... anyway here is a log of commands i used when i flashed today
pmbootstrap pull
pmbootstrap init
        Work path [/home/mast3r/.local/var/pmbootstrap]: enter
        Channel [edge]: enter
        Vendor [nvidia]: oneplus
        Kernel [mainline]: mainline
        device-oneplus-dumpling-nonfree-firmware: Firmware for GPU, Wi-Fi, Bluetooth etc. (mainline only, also needed for osk-sdl)
        Enable this package? (y/n) [y]: enter
        User interface [plasma-desktop]: enter
        Change them? (y/n) [n]: enter
        Extra packages [none]: enter
        Use this timezone instead of GMT? (y/n) [y]: enter
        Choose default locale for installation [en_GB.UTF-8]: enter
        Device hostname (short form, e.g. 'foo') [phone]: enter
        Would you like to copy your SSH public keys to the device? (y/n) [n]: enter
        Build outdated packages during 'pmbootstrap install'? (y/n) [y]: enter
        Zap existing chroots to apply configuration? (y/n) [y]: enter
 
pmbootstrap install
pmbootstrap flasher flash_kernel
pmbootstrap flasher flash_rootfs

**Comment by JamiKettunen** [comment] 2022-01-07 13:32
Huh, odd. Well I'll close this now. You can make [an issue on pmaports](https://gitlab.com/postmarketOS/pmaports/-/issues/new) and ping me there in case you have issues with postmarketOS in particular since it's not really a problem with the kernel itself most likely.

**Closed as completed by JamiKettunen** 2022-01-07 13:32 UTC
